### ISSUE TITLE
Regen Braking

### ISSUE THREAD

**Issue by chrischang5** [UBC-Solar/Simulation#100]

**Comment by chrischang5** [comment]
Algorithm `apply_deceleration` implementation idea
- Input: Speed Array `speed_kmh` with timing constraints applied and instantaneous deceleration
- Output: Speed Array `speed_kmh` with timing constraints applied and gradual deceleration

1. Identify indexes of instantaneous deceleration (which I think @ilyve has already done)
2. Consider any instantaneous deceleration moment that is defined to be a speed change from `v_1` to `v_2` over the period of `t_1` to `t_2` where
 `t_2 = t_1 + 1` and `v_1 > v_2`. In English, this means you go from a faster speed to a slower speed in the span of a second.

![image](https://user-images.githubusercontent.com/64388914/154133551-167d11b0-58fd-4197-a9f9-5b728f21de47.png)

3. Decide on some deceleration interval in seconds called `d`
- Maybe it is  3 seconds or maybe it scales with `delta(v1, v2)`
4. Now from `t_1 - d`, find an appropriate deceleration "step size" based on `(v_1 - v_2) / (d + 1)`. Replace `speed_kmh[t_1 - d: t_1]` with decreasing speeds based on your step size. Ex: `v_1 - step size * i` for `i in range(t_1 - d , t_1)`. This is may be a little unclear, so see the example below

Blue Curve: Output speed array
![image](https://user-images.githubusercontent.com/64388914/154134983-aed61220-4ea2-4b98-8c32-50bced273af8.png)

Ex: For a speed array [50, 50, 50, 50, 0, 0, 0, 0] and `d = 3`
- The instant deceleration moment occurs between `v_1 = 50` and `v_2 = 0`.
- `t_1 = 3` and `t_2 = 4`.
- Deceleration step size: `(50 - 0) / (3 + 1) = 12.5`
Output array: [50, 37.5, 25, 12.5, 0, 0, 0, 0]

**Comment by ilyve** [comment]
I made a little demo for this implementation, there may be some issues with it I noted at the bottom but it should suffice for our purpose:

`
import numpy as np

speed_array = np.array([50, 50, 50, 50, 0, 0, 0, 0])


def generate_deceleration_array(initial_velocity, final_velocity, steps):
    step_size = (final_velocity + initial_velocity) / (steps + 1)
    return np.arange(initial_velocity, final_velocity, -step_size)[1:]


deceleration_array = generate_deceleration_array(50, 0, 3)


def apply_deceleration(input_speed_array):
    input_speed_array = input_speed_array.astype(float)
    acceleration_instances = np.diff(input_speed_array, prepend=[0])  # Prepending to align acceleration_instances array
    # with speed_array
    deceleration_instances = np.where(acceleration_instances < 0)[0]  # [0] must be added because np.where returns an
    # array with only one element
    for idx in deceleration_instances:
        print("Before:")
        print(input_speed_array)
        input_speed_array[idx - 3:idx] = deceleration_array
        print("After:")
        print(input_speed_array)


apply_deceleration(speed_array)

# NOTE: The step size must be small enough to not overwrite speeds that are not equal to the initial_velocity
#       ( If two instances of deceleration are too close to each other, the later one will overwrite the previous one)
# NOTE: There will be some distance lost with this method, but it'll be a negligible amount

`

**Comment by chrischang5** [comment]
Feedback: 

This looks good and I believe this will work. Of course, you'll have to scale this functionality to handle multiple deceleration changes in a speed array. 

To prove this works, also create small test cases which can be easy to reason about. As you might have learned in CPEN 221, you'll need to consider partitioning the input space. I'll need these for when you write PyTest unit tests for your method. 

1. Change the argument `steps` in `generate_deceleration_array` to something like `deceleration_interval`. Concretely, this is what it actually is in our problem statement. This will be much more readable and the variable will now have a meaningful name. This logic also applies to the `step_size` variable as well.
2. Please add a `verbose` flag as an argument to control when logging statements are outputted. This can aid debugging and development in the future.
