### ISSUE TITLE
Separating the battery charging and discharging model

### ISSUE THREAD

**Issue by mihirnimgade** [UBC-Solar/Simulation#51]
In reality, batteries do not have the same charging and discharging curves and during normal operation, the battery will move between different charging and discharging curves as shown in the image. 

The current battery simulation uses a single curve for both charging and discharging which likely causes a large amount of inaccuracy. Change the model to include separate curves for charging and discharging. 

NOTE: This information may not be available in the cell datasheet so we might need to wait till we have access to the battery before this can be implemented.

<img width="437" alt="Screenshot 2021-03-25 192035" src="https://user-images.githubusercontent.com/40799875/112484392-e66aaf80-8d9f-11eb-92e4-646a818038e7.png">

**Comment by chrischang5** [comment]
Where did this graph originally come from?

**Comment by mihirnimgade** [comment]
There's this book on the Google Drive called "A Solar Car Primer". The graph is on page 114.

**Comment by chrischang5** [comment]
Have to talk to BMS if there's any resources for the discharging curves
