### ISSUE TITLE
Speed Limit Paradox

### ISSUE THREAD

**Issue by chrischang5** [UBC-Solar/Simulation#62]
This issue outlines some limitations and reasonings in our simulation that I just can't get over as of now. This is essentially a chicken or the egg problem but the chicken represents vehicle speeds and the egg represents speed limits (or the other way around?).

Suppose that we want to add a speed limit feature. You don't want the car going too fast in residential areas or on highways, so you call a Speed Limit API to find the speed limits of each route coordinate. We will try to optimize distance given this new constraint on top of the other ones we already have. 

The issue starts when you get some optimized speed results. For a smaller example, maybe the simulation found the speeds [70, 80, 30] was particularly good for some route and yielded a maximum distance. The simulation's order of operations will calculate the car's coordinate at each timestep and produce some array of coordinates.

But, suppose the Speed Limit API found out that we sped during hours 1 and 2. What happens next? We already found that the speeds [70, 80, 30] should have yielded an optimal speed, but we certainly cannot drive that fast. 

Would the best option be to cap our speeds? Say the simulation had some `speed_limit_cap()` operation done on the speed array on it and the result turns out to be [50, 50, 30]. Is that guaranteed to still be the optimal result? I'm thinking no, but it could be close. What if the saved battery by traveling slower in those first two hours results in us being able to travel more quickly in that third hour? The answer is most likely "yea, probably" but quantifying this seems much harder.  

The photo below should show some kind of insight into what I described above. You have three factors that influence each other in a circular manner. You start with your input speeds and assume traveling at those speeds is possible. Later on, the Speed Limit API could show that traveling at those speeds isn't possible. Then, you must correct that assumption somehow. Perhaps you choose a new input speed array, but this risks ending up in another cycle 

![image](https://user-images.githubusercontent.com/64388914/121788033-e5ffda80-cb7e-11eb-9a43-fcfc0317f38f.png)

**Comment by mihirnimgade** [comment]
One solution to this could be to feedback the [50, 50, 30] array into the `run_model()` method and continue doing that until the speed array input and the speed-capped speed array that you get at the end are equivalent. Once that happens, you can be confident that the result you're getting is accurate. You can then pass on this result to the optimizer and it can go do its thing. I think this looping behaviour is easier to justify now that the `run_model` method runs really fast. The problem is that mathematically proving that the speed array will converge when you loop it sounds kinda impossible. I guess we can just try it and see how it goes.

**Comment by chrischang5** [comment]
To try to make converging behavior more likely, there can be some `Delta` variable where you can drive at most the `speed limit + Delta` km/h. It's like how you can go 55 on a 50 street and no one really cares. The only place where this would matter is like a school zone, but maybe this isn't even something we need to worry about.

I have some skepticism regarding refeeding the [50, 50, 30] array back into the model. From conversations with @huajustin, the simulation optimizer performs some random sampling initially so it's almost independent of that initial input array (At least I'm pretty sure it is). Will have to ask Justin about this again next meeting.

Another naive way of trying to verify that your input assumption correction is to save all the best speed arrays that the optimizer found. For each of these coordinate paths, you call on the Speed Limit API and compare that to your input speed. It could be the case that you filter runs that got you the greatest distance, but you ensure you get ones that are actually legal. Then, you could choose the best distance out of those legal runs.
