### ISSUE TITLE
Acceleration Infinite Loop

### ISSUE THREAD

**Issue by chrischang5** [UBC-Solar/Simulation#74]
There is an infinite loop occurring in the helpers.add_acceleration() function. I don't know how to fix it as of now, so we're going to disable it for now.

Steps to reproduce:
- Add a print statement to `helpers.add_acceleration` like so:

![image](https://user-images.githubusercontent.com/64388914/134220226-fa6e0f78-2540-4833-b889-4b9f572bfe96.png)

- Run `max_distance_from_speed_using_arrays.py`
- Let the optimizer phase run
- Wait until iteration 4
- Verify one of the print statements will print indefinitely.

Initial Ideas:
- There might be some missing condition in the while statement that is not being considered. However, I did not write this method so I don't know exactly how it works. If there is any way to remove this while loop or create a robust stopping condition, this would likely solve the problem.
- I don't think it's feasible to check the input speed array, as this issue occurs only during the optimizer phase and the optimizer decides what the input speed array is.

**Comment by mihirnimgade** [comment]
I can't see how this could possibly lead to an infinite loop, but I would try maybe replacing the `while` loops with equivalent `for` loops. If that doesn't work, it might just be an issue with the optimizer library we're using.

**Comment by chrischang5** [comment]
This entire bug doesn't really make that much sense. Neither the optimizer library nor the acceleration method changed and they've been working fine up until now. 

I like the idea of changing the `while` loop to a `for` loop though.

**Comment by chrischang5** [comment]
Another way to verify this (I haven't done this yet) would be to wrap a `tqdm` timer around the loop to see its progress. That can visually confirm whether or not it's an infinite loop. 

To better address this issue, you could also declare a max number of iterations or a timeout.

What I originally did was put the print statements in and noticed it was running for an absurdly long time compared to this function running in other optimizer iterations.

**Comment by mihirnimgade** [comment]
If the issue is only showing up when the optimizer is enabled, I definitely suspect the optimizer library is the issue. Did you update it on your local computer recently? Maybe there was a new version that has this bug. And yeah, go ahead and try the `tqdm` thing. Seems like a good approach.

**Comment by chrischang5** [comment]
Resolved in #119
